### ISSUE TITLE
Eager loaded data

### ISSUE THREAD

**Issue by ognjenm** [adamfairholm/Elasticquent#1]
How to index with eager loaded data?

**Comment by yswery** [comment]
```
$things = Stuff:with('things')->get();
$things->indexAll()
```

Do keep in mind that when you aply a search it will return the related data in array form (not as a model collection)

**Comment by adamfairholm** [comment]
Thanks, @yswery - I didn't even think of doing this - that works nicely even though you are correct it's just going to return the array and not the full model.
