### ISSUE TITLE
Failed to access when host url with username:password

### ISSUE THREAD

**Issue by yaofong** [adamfairholm/Elasticquent#41]
I am using facetflow.io, a hosted elasticsearch. 
Their url have an API KEY prepend to the cluster url, such as:

https://apikey:@example.azure.facetflow.io

When I put in this URL to the config.hosts, facetflow returned error 401, authentication failed.

No problem when I was using aws elasticsearch, as they doesn't prepend any credential to the url.

So I wonder is this a problem with elasticquent or there are some problem with my server?

regards,

**Comment by adamfairholm** [comment]
Hi @yaofong - This repo of Elasticquent is deprecated - you can find the new one at the link below:

https://github.com/elasticquent/Elasticquent

However, I don't think this issue has anything to do with Elasticquent - we are just using the official ES PHP API wrapper, so I'd recommend doing a test with just the official ES PHP library and your credentials and see if that works.
